version: "3"

services:
    app:
        build:
            args:
                DATABASE_IDS: "azjk,odsk,zjkd"
                DATABASE_PREFIX: "rlods-party-"
                NODE_ENV: production
                PROXY_SECRET: "..."
                PROXY_URL: "https://proxy.rlods.xyz/api"
