version: "3"

services:
  api:
    command: CompileDaemon -log-prefix=false -build="go install -v ./..." -command="/go/bin/api"
    volumes:
      - ./services/api:/go/src/api:ro

  app:
    build:
      args:
        DATABASE_ID: "test-rl-7ffe8"
        NODE_ENV: development
    command: npm run start
    tty: true
    volumes:
      - ./services/app:/home/node/app/services/app:delegated # delegated for coverage generation

  proxy:
    build:
      context: ./docker/proxy
    volumes:
      - ./docker/proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
      - 1936:1936
    depends_on:
      - api
      - api2
      - app
    restart: on-failure
