version: "3"

services:
    app:
        command: npm run start
        environment:
            NODE_ENV: development
        tty: true

    proxy:
        image: haproxy:1.8-alpine
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - 80:80
            - 1936:1936
        depends_on:
            - app
        restart: on-failure
