version: "3"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
            args:
                DATABASE_IDS: "erte"
                DATABASE_PREFIX: "rlods-test-party-"
                PROXY_SECRET: "..."
                PROXY_URL: "https://proxy.rlods.xyz/api"
        restart: on-failure
